In [12]:
#所有代码

from __future__ import division
from math import pi,sqrt,sin,cos

# a python binding of https://on4wp7.codeplex.com/SourceControl/changeset/view/21483#353936

# Krasovsky 1940
#
# a = 6378245.0, 1/f = 298.3
# b = a * (1 - f)
# ee = (a^2 - b^2) / a^2
a = 6378245.0
ee = 0.00669342162296594323

# World Geodetic System ==> Mars Geodetic System
def transform(wgLat, wgLon):
    """
    transform(latitude,longitude) , WGS84
    return (latitude,longitude) , GCJ02
    """
    if (outOfChina(wgLat, wgLon)):
        mgLat = wgLat
        mgLon = wgLon
        return
    dLat = transformLat(wgLon - 105.0, wgLat - 35.0)
    dLon = transformLon(wgLon - 105.0, wgLat - 35.0)
    radLat = wgLat / 180.0 * pi
    magic = sin(radLat)
    magic = 1 - ee * magic * magic
    sqrtMagic = sqrt(magic)
    dLat = (dLat * 180.0) / ((a * (1 - ee)) / (magic * sqrtMagic) * pi)
    dLon = (dLon * 180.0) / (a / sqrtMagic * cos(radLat) * pi)
    mgLat = wgLat + dLat
    mgLon = wgLon + dLon
    return mgLat,mgLon

def outOfChina(lat, lon):
    if (lon < 72.004 or lon > 137.8347):
        return True
    if (lat < 0.8293 or lat > 55.8271):
        return True
    return False

def transformLat(x, y):
    ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * sqrt(abs(x))
    ret += (20.0 * sin(6.0 * x * pi) + 20.0 * sin(2.0 * x * pi)) * 2.0 / 3.0
    ret += (20.0 * sin(y * pi) + 40.0 * sin(y / 3.0 * pi)) * 2.0 / 3.0
    ret += (160.0 * sin(y / 12.0 * pi) + 320 * sin(y * pi / 30.0)) * 2.0 / 3.0
    return ret

def transformLon(x, y):
    ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * sqrt(abs(x))
    ret += (20.0 * sin(6.0 * x * pi) + 20.0 * sin(2.0 * x * pi)) * 2.0 / 3.0
    ret += (20.0 * sin(x * pi) + 40.0 * sin(x / 3.0 * pi)) * 2.0 / 3.0
    ret += (150.0 * sin(x / 12.0 * pi) + 300.0 * sin(x / 30.0 * pi)) * 2.0 / 3.0
    return ret

if __name__ == "__main__":
    WGS84_Lat = 39.990205
    WGS84_Long = 116.327847
    print (transform(WGS84_Lat,WGS84_Long))

(39.991519388614314, 116.3339908951279)

In [3]:
import pandas as pd

In [4]:
data=pd.read_excel("Schooldata_cleaned.xlsx")

In [5]:
data.head()

,name,address,district,assignmode,primaryormiddle,quality,Unnamed: 6,WGS84lat,WGS84lon
0,北京市陈经纶中学嘉铭分校,北京市朝阳区北苑路86号,Chaoyang,Nineyears,primary,3,NaN,40.001021,116.417500
1,北京市十一学校一分校,北京市海淀区万寿路街道翠微路19号,Haidian,Nineyears,primary,4,NaN,39.898893,116.278256
2,北京市育鸿学校,北京市海淀区复兴路14号,Haidian,Nineyears,primary,4,NaN,39.897561,116.307324
3,中国教育科学研究院朝阳实验学校(中学校部),北京市朝阳区安贞西里一区13号楼,Chaoyang,Nineyears,primary,5,NaN,39.972325,116.392909
4,北京市海淀区崛起实验学校,北京市海淀区菊园小区11号楼,Haidian,Nineyears,primary,5,NaN,40.032232,116.281552

In [8]:
transform(40.001021, 116.417500)[0]

40.002423844038546

In [7]:
data["glat"]=1
data["glon"]=1
data.shape

(734, 11)

In [32]:

for i in range(0,len(data),1):
    
    lat1=data.iloc[i,7]
    lat1=float(lat1)
    lon1=data.iloc[i,8]
    lon1=float(lon1)
    #所有代码

    

# a python binding of https://on4wp7.codeplex.com/SourceControl/changeset/view/21483#353936

# Krasovsky 1940
#
# a = 6378245.0, 1/f = 298.3
# b = a * (1 - f)
# ee = (a^2 - b^2) / a^2
    a = 6378245.0
    ee = 0.00669342162296594323

# World Geodetic System ==> Mars Geodetic System
    def transform(wgLat, wgLon):
        if (outOfChina(wgLat, wgLon)):
            mgLat = wgLat
            mgLon = wgLon
            return
        dLat = transformLat(wgLon - 105.0, wgLat - 35.0)
        dLon = transformLon(wgLon - 105.0, wgLat - 35.0)
        radLat = wgLat / 180.0 * pi
        magic = sin(radLat)
        magic = 1 - ee * magic * magic
        sqrtMagic = sqrt(magic)
        dLat = (dLat * 180.0) / ((a * (1 - ee)) / (magic * sqrtMagic) * pi)
        dLon = (dLon * 180.0) / (a / sqrtMagic * cos(radLat) * pi)
        mgLat = wgLat + dLat
        mgLon = wgLon + dLon
        return mgLat,mgLon

    def outOfChina(lat, lon):
        if (lon < 72.004 or lon > 137.8347):
            return True
        if (lat < 0.8293 or lat > 55.8271):
            return True
        return False

    def transformLat(x, y):
        ret = -100.0 + 2.0 * x + 3.0 * y + 0.2 * y * y + 0.1 * x * y + 0.2 * sqrt(abs(x))
        ret += (20.0 * sin(6.0 * x * pi) + 20.0 * sin(2.0 * x * pi)) * 2.0 / 3.0
        ret += (20.0 * sin(y * pi) + 40.0 * sin(y / 3.0 * pi)) * 2.0 / 3.0
        ret += (160.0 * sin(y / 12.0 * pi) + 320 * sin(y * pi / 30.0)) * 2.0 / 3.0
        return ret

    def transformLon(x, y):
        ret = 300.0 + x + 2.0 * y + 0.1 * x * x + 0.1 * x * y + 0.1 * sqrt(abs(x))
        ret += (20.0 * sin(6.0 * x * pi) + 20.0 * sin(2.0 * x * pi)) * 2.0 / 3.0
        ret += (20.0 * sin(x * pi) + 40.0 * sin(x / 3.0 * pi)) * 2.0 / 3.0
        ret += (150.0 * sin(x / 12.0 * pi) + 300.0 * sin(x / 30.0 * pi)) * 2.0 / 3.0
        return ret

    if __name__ == "__main__":
        WGS84_Lat = 39.990205
        WGS84_Long = 116.327847
    
    
    wj=transform(lat1,lon1)
    try:
        data.iloc[i,9]=wj[0]
        data.iloc[i,10]=wj[1]
    except:
        data.iloc[i,9]=0
        data.iloc[i,10]=0
        print(i)

71
545

In [30]:
data

,name,address,district,assignmode,primaryormiddle,quality,Unnamed: 6,WGS84lat,WGS84lon,glat,glon
0,北京市陈经纶中学嘉铭分校,北京市朝阳区北苑路86号,Chaoyang,Nineyears,primary,3,NaN,40.001021,116.417500,40.002424,116.423748
1,北京市十一学校一分校,北京市海淀区万寿路街道翠微路19号,Haidian,Nineyears,primary,4,NaN,39.898893,116.278256,39.900124,116.284296
2,北京市育鸿学校,北京市海淀区复兴路14号,Haidian,Nineyears,primary,4,NaN,39.897561,116.307324,39.898833,116.313411
3,中国教育科学研究院朝阳实验学校(中学校部),北京市朝阳区安贞西里一区13号楼,Chaoyang,Nineyears,primary,5,NaN,39.972325,116.392909,39.973729,116.399159
4,北京市海淀区崛起实验学校,北京市海淀区菊园小区11号楼,Haidian,Nineyears,primary,5,NaN,40.032232,116.281552,40.033472,116.287612
5,北京市海淀北部新区实验学校,北京市海淀区苏家坨镇西小营村,Haidian,Nineyears,primary,5,NaN,40.061394,116.115189,40.062792,116.121518
6,北京市中科启元学校,北京市海淀区中关村南三街10号,Haidian,Nineyears,primary,5,NaN,39.981317,116.322186,39.982621,116.328315
7,首都师范大学附属玉泉学校,北京市海淀区闵庄南路,Haidian,Nineyears,primary,5,NaN,39.964871,116.241533,39.966090,116.247574
8,首都师范大学附属玉泉学校,北京市海淀区闵庄南路,Haidian,Nineyears,primary,5,NaN,39.964871,116.241533,39.966090,116.247574
9,北京市和平北路学校,北京市东城区安外大街168号,Dongcheng,Nineyears,primary,5,NaN,39.952800,116.403426,39.954206,116.409676
10,北京市第一一五中学,北京市东城区天坛东路13号,Dongcheng,Nineyears,primary,5,NaN,39.879484,116.413244,39.880884,116.419480
11,北京市正泽学校（新增） 非营利民办学校,北京市西城区丁章胡同1号,Xicheng,Nineyears,primary,5,NaN,39.922297,116.383022,39.923693,116.389259
12,北京市朝阳区安民学校,北京市朝阳区和平街十四区9号楼东,Chaoyang,Nineyears,primary,5,NaN,39.958757,116.421009,39.960156,116.427248
13,北京市朝阳区百年实验学校,北京市朝阳区崔各庄乡何各庄村顺白路300号,Chaoyang,Nineyears,primary,5,NaN,40.041013,116.490353,40.042269,116.496413
14,北京市朝阳区星河双语学校,北京市朝阳区十八里店乡十里河村139号,Chaoyang,Nineyears,primary,5,NaN,39.860342,116.455126,39.861684,116.461283
15,北京市朝阳区金色摇篮全程实验学校,北京市朝阳区慧忠北里119号,Chaoyang,Nineyears,primary,5,NaN,40.006543,116.398581,40.007950,116.404838
16,北京市朝阳外国语学校分校,北京市朝阳区来广营清河营中街148-1号,Chaoyang,Nineyears,primary,5,NaN,40.047417,116.432277,40.048808,116.438512
17,北京师范大学三帆中学朝阳学校,北京市朝阳区南湖南路12号,Chaoyang,Nineyears,primary,5,NaN,39.961218,116.369055,39.962601,116.375280
18,北京市新教育实验学校,北京市朝阳区常营地区住欣家园102号,Chaoyang,Nineyears,primary,5,NaN,39.921517,116.609865,39.922559,116.615659
19,北京市第八十中学实验学校康营分校,北京市朝阳区孙河乡康营家园14区108号,Chaoyang,Nineyears,primary,5,NaN,40.034773,116.529556,40.035915,116.535471
20,北京市陈经纶中学分校,北京市朝阳区利泽西街4号院,Chaoyang,Nineyears,primary,5,NaN,40.006675,116.459834,40.008012,116.465996
21,北京工业大学附属中学英才分校,北京市朝阳区磨房北里230号,Chaoyang,Nineyears,primary,5,NaN,39.895277,116.443201,39.896643,116.449393
22,北京市日坛中学实验学校,北京市朝阳区八里庄东里十号,Chaoyang,Nineyears,primary,5,NaN,39.922966,116.497847,39.924194,116.503863
23,北京市金盏学校,北京市朝阳区金盏大街1号,Chaoyang,Nineyears,primary,5,NaN,40.003318,116.561524,40.004390,116.567350
24,北京教育学院朝阳分院附属学校,北京市朝阳区慈云里甲1号,Chaoyang,Nineyears,primary,5,NaN,39.959848,116.378444,39.961242,116.384681
25,北京市中央商务区实验学校,北京市朝阳区西大望路下甸甲1号,Chaoyang,Nineyears,primary,5,NaN,39.922297,116.383022,39.923693,116.389259
26,北京市第八十中学枣营分校,北京市朝阳区枣营南里1号,Chaoyang,Nineyears,primary,5,NaN,39.926965,116.452885,39.928314,116.459058
27,北京市樱花园实验学校,北京市朝阳区樱花园小区16号楼,Chaoyang,Nineyears,primary,5,NaN,39.972581,116.415239,39.973984,116.421486
28,北京市望京实验学校,北京市朝阳区望京西园三区313楼,Chaoyang,Nineyears,primary,5,NaN,39.998413,116.470686,39.999722,116.476811
29,北京市第九十四中学机场分校,北京市朝阳区首都机场燕翔西里19号,Chaoyang,Nineyears,primary,5,NaN,40.045122,116.586906,40.046169,116.592709
...,...,...,...,...,...,...,...,...,...,...,...
704,首都师范大学附属中学,北京市海淀区北洼路33号,Haidian,None,middle,2,NaN,39.928596,116.295062,40.002424,116.423748
705,北京大学附属中学,北京市海淀区大泥湾路甲82号,Haidian,None,middle,2,NaN,39.975882,116.314085,40.002424,116.423748
706,北方交通大学附属中学,北京市海淀区恩济庄46号,Haidian,None,middle,3,NaN,39.930707,116.277809,40.002424,116.423748
707,北京市北达资源中学,北京市海淀区北京大学畅春园,Haidian,None,middle,4,NaN,39.992669,116.294579,40.002424,116.423748
708,北京市第四十七中学,北京市海淀区苏家坨镇北安河村环谷园路8号,Haidian,None,middle,5,NaN,40.064797,116.108123,40.002424,116.423748
709,北京理工大学附属中学分校,北京市海淀区紫竹院南路11号,Haidian,None,middle,5,NaN,39.933904,116.313472,40.002424,116.423748
710,北方交通大学附属中学第二分校,北京市海淀区西外高梁桥斜街3号,Haidian,None,middle,5,NaN,39.950342,116.329853,40.002424,116.423748
711,北京市六一中学,北京市海淀区定慧西里17号,Haidian,None,middle,5,NaN,39.921701,116.273847,40.002424,116.423748
712,北京外国语大学附属中学,北京市海淀区万寿寺北里14号,Haidian,None,middle,5,NaN,39.950937,116.306106,40.002424,116.423748
713,北大附中香山学校,北京市海淀区香山南辛村1号,Haidian,None,middle,5,NaN,39.987438,116.206773,40.002424,116.423748
714,中国矿业大学（北京）附属中学,北京市海淀区学院路丁11号,Haidian,None,middle,5,NaN,39.995573,116.340677,40.002424,116.423748
715,北方交通大学附属中学分校,北京市海淀区学院南路一号,Haidian,None,middle,5,NaN,39.956848,116.354400,40.002424,116.423748
716,中国人民大学附属中学翠微学校,北京市海淀区翠微路1号,Haidian,None,middle,5,NaN,39.912115,116.295802,40.002424,116.423748
717,首都师范大学第二附属中学,北京市海淀区增光路50号,Haidian,None,middle,5,NaN,39.926392,116.308399,40.002424,116.423748
718,人大附中西山学校,北京市海淀区马连洼南路9号,Haidian,None,middle,5,NaN,40.030860,116.276804,40.002424,116.423748
719,中国人民大学附属中学第二分校,北京市海淀区蓝靛厂路25号,Haidian,None,middle,5,NaN,39.965352,116.271621,40.002424,116.423748
720,北京市清华育才实验学校,北京市海淀区闵庄路56号,Haidian,None,middle,5,NaN,39.969265,116.225910,40.002424,116.423748
721,北京市仕尚中学,北京市海淀区上庄路2号,Haidian,None,middle,5,NaN,40.099078,116.207559,40.002424,116.423748
722,清华大学附属中学永丰学校,北京市海淀区北清路永丰嘉园西侧百旺杏林湾西北角,Haidian,None,middle,5,NaN,40.074517,116.250966,40.002424,116.423748
723,北京师范大学附属实验中学,北京市西城区二龙路14号,Xicheng,None,middle,1,NaN,39.909539,116.361246,40.002424,116.423748
724,北京市第二中学,北京市东城区内务部街15号,Dongcheng,None,middle,2,NaN,39.918511,116.417142,40.002424,116.423748
725,北京市第五中学,北京市东城区细管胡同13号,Dongcheng,None,middle,2,NaN,39.936304,116.408165,40.002424,116.423748
726,北京市清华志清中学,北京市海淀区体育大学南侧,Haidian,None,middle,5,NaN,40.019543,116.311518,40.002424,116.423748
727,北京市一零一实验学校,北京市海淀区双榆树东里35号,Haidian,None,middle,5,NaN,39.967459,116.321290,40.002424,116.423748
728,北京市外国语学校,北京市东城区报房胡同82号,Dongcheng,None,middle,5,NaN,39.920418,116.407110,40.002424,116.423748
729,北京市新光中学,北京市西城区西黄城根北街6号,Xicheng,None,middle,5,NaN,39.922297,116.383022,40.002424,116.423748
730,北京西藏中学,北京市朝阳区北四环东路高原街一号,Chaoyang,None,middle,5,NaN,39.986778,116.420743,40.002424,116.423748
731,中央民族大学附属中学,北京市海淀区法华寺甲5号,Haidian,None,middle,5,NaN,39.949849,116.310656,40.002424,116.423748
732,北京市清华志清中学,北京市海淀区体育大学南侧,Haidian,None,middle,5,NaN,40.019543,116.311518,40.002424,116.423748
733,北京市一零一实验学校,北京市海淀区双榆树东里35号,Haidian,None,middle,5,NaN,39.967459,116.321290,40.002424,116.423748

In [33]:
data.shape

(734, 11)

In [21]:
data1=pd.read_excel("translation_Schooldata_cleaned.xlsx")

In [22]:
data1.shape

(734, 9)

In [34]:
data.to_csv("google_crs2.csv",encoding="utf_8_sig")

In [24]:
# import the SQLAlchemy libraries
from sqlalchemy import create_engine

# create the connection string to the MySQL database
# replace USERNAME and PASSWORD with your own credentials 
engine = create_engine('mysql+pymysql://ucfnjwa:yapisodexe@dev.spatialdatacapture.org:3306/ucfnjwa?charset=utf8"')

# make the connection to the database
conn = engine.raw_connection()

ModuleNotFoundError: No module named 'pymysql'